/*Enunciado
	Para entrar a la montaña rusa interno en las alturas se requiere
 	tener al menos 7 años Y medir más de 1,50 metros. 
 	Completá el siguiente cuadro a mano según los requisitos 
 	y luego escribí el programa que permita, ejecutándolo cada vez para cada niño 
 	y según las edades y estaturas ingresadas por el usuario, 
 	obtener los mismos resultados para los siguientes datos: [EC]
 	
 	Nombre
 	Edad
 	Altura
 	¿Entra al juego? (V/F)
 	
 	Juan   María   Luis  Ana
 	5      7       8     9
 	1.45   1.23    1.51  1.39
*/