/*Enunciado
    Existen dos reglas que identifican dos conjuntos de valores:
    El número es de un solo dígito
    El número es impar.
    A partir de estas reglas, realizá un programa que permita 
    ingresar un número entero. Debe asignar el valor que corresponda a las variables 
    booleanas esDeUnSoloDigito, eslmpar, estaEnAmbosGrupos y noEstaEnNingunGrupo
    el valor Verdadero o Falso, según corresponda,
    para indicar si el valor número ingresado pertenece o no a cada conjunto.
    AI terminar el programa debe informar el número cargado y las cuatros variables lógicas.
    Definí un lote de prueba de varios números y probá el algoritmo,
    escribiendo los resultados tal como se hizo en los ejercicios anteriores.
*/

